// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as WithApollo from "../helpers/withApollo";

function withApollo(prim) {
  return WithApollo.default(prim);
}

var Apollo = /* module */[/* withApollo */withApollo];

export {
  Apollo ,
  
}
/* ../helpers/withApollo Not a pure module */
