// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as WithApollo from "../helpers/withApollo";

function withApollo(prim) {
  return WithApollo.default(prim);
}

var Apollo = {
  withApollo: withApollo
};

export {
  Apollo ,
  
}
/* ../helpers/withApollo Not a pure module */
