// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as WithApollo from "../helpers/withApollo";

var Link = /* module */[];

var Head = /* module */[];

var $$Error = /* module */[];

var Router = /* module */[];

function withApollo(prim) {
  return WithApollo.default(prim);
}

var Apollo = /* module */[/* withApollo */withApollo];

export {
  Link ,
  Head ,
  $$Error ,
  Router ,
  Apollo ,
  
}
/* ../helpers/withApollo Not a pure module */
