// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Hoc from "../bindings/Hoc.bs.js";
import * as React from "react";
import * as Subreddit from "../components/Subreddit.bs.js";

function ste(prim) {
  return prim;
}

function Index(Props) {
  return React.createElement(Subreddit.make, {
              name: "reactJs"
            });
}

var $$default = Hoc.Apollo.withApollo(Index);

var make = Index;

var index = Index;

export {
  ste ,
  make ,
  index ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
