/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const PickerBS = require('./Picker.bs');

export const $$default: (_1:{
  readonly className?: string; 
  readonly onChange?: ((_1:((_1:string) => string)) => void); 
  readonly options: string[]; 
  readonly value?: string; 
  readonly valueUseState?: [string, ((_1:((_1:string) => string)) => void)]
}) => JSX.Element = PickerBS.default;

export default $$default;
