/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const SubredditBS = require('./Subreddit.bs');

// tslint:disable-next-line:interface-over-type-literal
export type Props = { readonly name: string };

export const $$default: React.ComponentType<{ readonly name: string }> = SubredditBS.default;

export default $$default;
