// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";

function withTestID(testID, element) {
  return React.cloneElement(element, {
              "data-testid": testID
            });
}

export {
  withTestID ,
  
}
/* react Not a pure module */
