/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const indexBS = require('./index.bs');

export const $$default: (_1:{}) => JSX.Element = indexBS.default;

export default $$default;
