/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const indexBS = require('./index.bs');

// tslint:disable-next-line:interface-over-type-literal
export type Index_Props = {};

export const Index: React.ComponentType<{}> = indexBS.index;

// tslint:disable-next-line:interface-over-type-literal
export type Props = {};

export const $$default: React.ComponentType<{}> = indexBS.default;

export default $$default;
